twitter_key: "7dqHVX0fWBJTsIISWLTtLMaRr"
twitter_secret: "fFsBaU917Ky9vbq5yPdFrvSZrnsQTRz4Rg2vjIl5BDl7vhAXFT"
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> parent of b491861... secret keys suck





<<<<<<< HEAD
>>>>>>> parent of b365923... dumb
=======
>>>>>>> parent of b491861... secret keys suck
